version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://db:27017
    ports:
      - "8080:8080"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
