name: Build documentation

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  pages: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Unzip
        run: unzip resources/documentation/webHelpHOME2-all.zip -d documentation
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./documentation
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
